template-file-path: vpc-network-template.yaml
stack-name: vpc-network-stack
region: us-west-2
parameters:
  VPC1Environment: Production
  VPC2Environment: Development
tags:
  Project: VPC-Network
  ManagedBy: GitSync

